export type Expert = {
  id?: string;
  _id?: string;
  first_name?: string;
  last_name?: string;
  name?: string;
  email?: string;
  phone?: string;
  role?: string;
  bio?: string;
  about?: string;
  experience_years?: number | string | null;
  profile_image?: string | null;
  cover_image?: string | null;
  professional_title?: string | null;
  profession?: string | null;
  specialization?: string | null;
  average_rating?: string | number | null;
  total_reviews?: number;
  total_sessions?: number;
  is_verified?: boolean;
  verification_status?: string | null;
  is_active?: boolean;
  consultation_fee?: number | string | null;
  whatsapp_number?: string | null;
  city?: string | null;
  state?: string | null;
  languages?: string[] | string | null;
  education?: string[] | string | null;
  certifications?: string[] | string | null;
  categories?: unknown[];
  [key: string]: unknown;
};
